# Generated by Django 3.0.2 on 2020-10-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField(blank=True, null=True, verbose_name='calories')),
                ('total_fat', models.FloatField(blank=True, null=True, verbose_name='total fat')),
                ('sugar', models.FloatField(blank=True, null=True)),
                ('sodium', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('saturated_fat', models.FloatField(blank=True, null=True, verbose_name='saturated fat')),
            ],
        ),
    ]
