# Generated by Django 3.0.2 on 2020-10-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0002_nutrition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'dishes'},
        ),
        migrations.AddField(
            model_name='dish',
            name='img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='dishes'),
        ),
    ]
