# Generated by Django 3.0.2 on 2020-10-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0004_auto_20201005_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='desciription',
            new_name='description',
        ),
    ]
