# Generated by Django 3.0.2 on 2020-10-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0005_auto_20201005_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
