# Generated by Django 3.0.2 on 2020-10-05 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_module', '0006_step_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_module.dish'),
        ),
    ]
